// frontend/src/components/prelobby/Navbar.jsx
import React from "react";
import { Link } from "gatsby";

export default function Navbar() {
    return (
        <nav className="relative px-4 py-4 flex justify-center items-center h-16 lg:gap-48 md:gap-28">
            <ul className="flex items-center gap-6">
                <li>
                    <Link to="/" className="text-sm text-primary font-bold">
                        Home
                    </Link>
                </li>
                {/*
                <li className="text-gray-300">
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        stroke="currentColor"
                        className="w-4 h-4 current-fill"
                        viewBox="0 0 24 24"
                    >
                        <path d="M12 5v0m0 7v0m0 7v0m0-13a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z" />
                    </svg>
                </li>
                */}
                <li>
                    <Link
                        to="#"
                        className="text-sm text-gray-400 hover:text-gray-500"
                    >
                        Documentation
                    </Link>
                </li>
                {/*
                <li className="text-gray-300">
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        stroke="currentColor"
                        className="w-4 h-4 current-fill"
                        viewBox="0 0 24 24"
                    >
                        <path d="M12 5v0m0 7v0m0 7v0m0-13a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z" />
                    </svg>
                </li>
                */}
                <li>
                    <Link
                        to="#"
                        className="text-sm text-gray-400 hover:text-gray-500"
                    >
                        Settings
                    </Link>
                </li>
            </ul>
        </nav>
    );
}

// frontend/components/prelobby_game/navbar/Navbar.vue
<template>
    <ReturnToHome />
    <nav
        class="relative px-4 py-4 flex justify-center items-center h-16 lg:gap-48 md:gap-28"
    >
        <router-link
            to="#"
            class="text-3xl font-bold leading-none hidden md:block w-32"
        >
        </router-link>
        <ul class="flex items-center gap-6" style="margin-right: 15px">
            <li>
                <button
                    class="text-sm hover:text-primary transition-colors duration-80"
                    @click="returnToHomepage"
                >
                    Home
                </button>
            </li>
            <li>
                <Documentation />
            </li>
            <li>
                <router-link
                    to="#"
                    class="text-sm hover:text-primary transition-colors duration-80"
                    >Settings</router-link
                >
            </li>
            <ThemeDropdown class="block md:hidden" :small="true" />
        </ul>
        <ThemeDropdown class="hidden md:block ml-6 md:ml-0" :small="false" />
        <Sidebar />
    </nav>
</template>

<script setup>
import ThemeDropdown from "~/components/ThemeDropdown.vue";
import ReturnToHome from "~/components/prelobby_game/navbar/ReturnToHome.vue";

const returnToHomepage = () => {
    my_modal_1.showModal();
};
</script>
