// frontend/components/homepage/Untertext.vue
<template>
    <div class="text-sm text-primary sm:w-1/2 w-full text-center">
        Planning Poker is an Agile estimation technique where team members use
        cards to vote on the complexity of tasks, promoting collaboration and
        consensus in project planning.
    </div>
</template>

<script setup></script>

<style lang="scss" scoped></style>

// frontend/src/components/homepage/Untertext.tsx
import React from "react";

export default function Untertext() {
    return (
        <div className="text-sm text-primary sm:w-1/2 w-full text-center">
            Planning Poker is an Agile estimation technique where team members
            use cards to vote on the complexity of tasks, promoting
            collaboration and consensus in project planning.
        </div>
    );
}
